<a href="https://colab.research.google.com/github/vit050587/Linear-algebra/blob/master/linal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.linalg import norm
import matplotlib.pyplot as plt

# Урок 1

## Задание 1.1

Исследовать на линейную зависимость:
$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$

$$f_{3}(x)=f_{2}(x)+ x$$
$$x=f_{3}(x)-f_{2}(x), f_{4}(x)=f_{3}(x)-f_{2}(x)-f_{1}(x)$$
Вывод: один из векторов - линейная комибнация остальных, значит они линейно зависимы.

## Задание 2.1

Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}.$$

$$f_{4}(x)=f_{3}(x)+2f_{2}(x)+0.5f_{1}(x)$$
Вывод: они линейно зависимы.

## Задание 3.1

Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.

$$x=b_{2}+3b_{3}+0.5b_{1}$$

## Задание 4.1

Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

   а) в базисе $1$, $x$, $x^{2}$;

   б) в базисе $x^{2}$, $x-1$, $1$.

a) $$x=3b_{3}-2b_{2}+2b_{1}$$
б) $$x=3b_{1}-2b_{2}+0*b_{3}$$

## Задание 5.1

Установить, является ли линейным подпространством:

а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;

б) все векторы, являющиеся линейными комбинациями данных векторов  {u1,u2,...,un} .

а) $$(0,a,b)+(c,0,d)=(c,a,b+d)$$
Вывод: не принадлежат указанному множеству веторов.

б) Вывод: если векторы являются линейнными комбинациями, значит они линейно зависимы и значит являются линейным подпространством


## Задание 1.2

Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

In [ ]:
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])
print(f'вариант a)(x, y) =\t{x.dot(y)}')
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
print(f'варианти б)(x, y) =\t{x.dot(y)}')

вариант a)(x, y) =	33
варианти б)(x, y) =	-23


## Задание 2.2

Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.

In [ ]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])
print(f'l1 норма вектора a:\t{norm(a, ord=1)}')
print(f'l1 норма вектора b:\t{norm(b, ord=1)}')
print(f'l2 норма вектора a:\t{norm(a, ord=2)}')
print(f'l2 норма вектора b:\t{norm(b, ord=2)}')
cos_phi = np.dot(a, b) / norm(a) / norm(b)
print(f'Косинус угла между a и b: {cos_phi:.2f}')
print(f'Угол между a и b: {np.arccos(cos_phi):.2f}')

l1 норма вектора a:	10.0
l1 норма вектора b:	19.0
l2 норма вектора a:	6.0
l2 норма вектора b:	13.0
Косинус угла между a и b: 0.90
Угол между a и b: 0.46


## Задание 3.2

Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?

а) Да, но при условии если $x_{1} \mbox{ и } x_{2}$ будут коллинеарны. Если же они не коллинеарны, то норма от $x_{1} + x_{2}$ будет меньше, чем нормы от этих векторов по отдельности а значит не выполнится третья аксиома для Евклидова пространства: $(x_{1}+x_{2},y)=(x_{1},y)+(x_{2},y)$<br>
б) Да, так как выполнятся все аксиомы для Евклидова пространства

## Задание 4.2

Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>
б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>
в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>
г) $(1,0,0),(0,1,0),(0,0,1)?$ 

# Урок 2

## Задание 1.1

Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    

In [ ]:
# A — матрица 4×2 , B — матрица 4×2
A = np.ones((4,2))
B = np.ones((4,2))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Матрица B
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


ValueError: ignored

In [ ]:
# A — матрица 2×5 , B — матрица 5×3
A = np.ones((2,5))
B = np.ones((5,3))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Матрица B
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Матрица AB
[[5. 5. 5.]
 [5. 5. 5.]]


ValueError: ignored

In [ ]:
# A — матрица 8×3 , B — матрица 3×8
A = np.ones((8,3))
B = np.ones((3,8))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Матрица B
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
Матрица AB
[[3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]]
Матрица BA
[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


In [ ]:
# A — квадратная матрица 4×4 , B — квадратная матрица 4×4
A = np.ones((4,4))
B = np.ones((4,4))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Матрица B
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Матрица AB
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
Матрица BA
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


## Задание 2.1

Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [ ]:
A = np.array([[1,-2],[3,0]])
B = np.array([[4,-1],[0,5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A+B\n{A+B}')
print(f'Матрица AxB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A+B
[[ 5 -3]
 [ 3  5]]
Матрица AxB
[[  4 -11]
 [ 12  -3]]


## Задание 3.1

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [ ]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C\n{B}')
print(f'Матрица 3A-2B+4C\n{3*A+(-2)*B+4*C}')

Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица C
[[ 0  5]
 [ 2 -1]]
Матрица 3A-2B+4C
[[ 11  -5]
 [  9 -12]]


## Задание 4.1

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


In [ ]:
A = np.array([[4,1],[5,-2],[2,3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
print(f'матрица A*AT:\n{np.dot(A,A.T)}')
print(f'матрица AT*A:\n{np.dot(A.T,A)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
матрица A*AT:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
матрица AT*A:
[[45  0]
 [ 0 14]]


## Задание 5.1*

Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def matrix_multiplication(m1,m2):
    s=0     # сумма
    t=[]    # временная матрица
    m3=[]   # конечная матрица
    if len(m2)!=len(m1[0]):
        print("Матрицы не соответствуют друг другу и не могут быть перемножены")        
    else:
        r1=len(m1)      # количество строк в первой матрице
        c1=len(m1[0])   # количество столбцов в первой матрице  
        r2=c1           # количество строк во второй матрице
        c2=len(m2[0])   # количество столбцов во второй матрице
        for z in range(0,r1):
            for j in range(0,c2):
                for i in range(0,c1):
                   s=s+m1[z][i]*m2[i][j]
                t.append(s)
                s=0
            m3.append(t)
            t=[]           
    return m3

## Задание 1

Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a) $$detA=sin^2(x)-(-cos^2(x))=1$$


In [ ]:
# б)
detA=4*(5*9-0*1)-2*(0*9-0*1)+3*(0*0-0*5)
print(detA)
print('*' * 50)
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

180
**************************************************
Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [ ]:
# в)
detA=1*(5*9-8*6)-2*(4*9-6*7)+3*(4*8-5*7)
print(detA)
print('*' * 50)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

0
**************************************************
Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


## Задание 2

Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

a) $$det(A^2)=det(A)*det(A)=16$$
б) $$det(AT)=det(A)=4$$
в) $$det(2A)=2*det(A)=8$$

## Задание 3

Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [ ]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


## Задание 4

Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [ ]:
# а)
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица варианта а):\n{a}')
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы варианта а): {r}')
print('*' * 50)
# б)
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица варианта б):\n{b}')
r = np.linalg.matrix_rank(b)
print(f'Ранг матрицы варианта б): {r}')

Матрица варианта а):
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы варианта а): 2
**************************************************
Матрица варианта б):
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы варианта б): 3
