<a href="https://colab.research.google.com/github/vit050587/Linear-algebra/blob/master/LinAl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from numpy.linalg import norm
import matplotlib.pyplot as plt

# Урок 1

## Задание 1

Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

In [4]:
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])
print(f'вариант a)(x, y) =\t{x.dot(y)}')
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
print(f'варианти б)(x, y) =\t{x.dot(y)}')

вариант a)(x, y) =	33
варианти б)(x, y) =	-23


## Задание 2

Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.

In [5]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])
print(f'l1 норма вектора a:\t{norm(a, ord=1)}')
print(f'l1 норма вектора b:\t{norm(b, ord=1)}')
print(f'l2 норма вектора a:\t{norm(a, ord=2)}')
print(f'l2 норма вектора b:\t{norm(b, ord=2)}')
cos_phi = np.dot(a, b) / norm(a) / norm(b)
print(f'Косинус угла между a и b: {cos_phi:.2f}')
print(f'Угол между a и b: {np.arccos(cos_phi):.2f}')

l1 норма вектора a:	10.0
l1 норма вектора b:	19.0
l2 норма вектора a:	6.0
l2 норма вектора b:	13.0
Косинус угла между a и b: 0.90
Угол между a и b: 0.46


## Задание 3

Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?

а) Да, но при условии если $x_{1} \mbox{ и } x_{2}$ будут коллинеарны. Если же они не коллинеарны, то норма от $x_{1} + x_{2}$ будет меньше, чем нормы от этих векторов по отдельности а значит не выполнится третья аксиома для Евклидова пространства: $(x_{1}+x_{2},y)=(x_{1},y)+(x_{2},y)$<br>
б) Да, так как выполнятся все аксиомы для Евклидова пространства

## Задание 4

Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>
б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>
в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>
г) $(1,0,0),(0,1,0),(0,0,1)?$ 

# Урок 2

## Задание 1

Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a) $$detA=sin^2(x)-(-cos^2(x))=1$$


In [9]:
# б)
detA=4*(5*9-0*1)-2*(0*9-0*1)+3*(0*0-0*5)
print(detA)
print('*' * 50)
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

180
**************************************************
Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [10]:
# в)
detA=1*(5*9-8*6)-2*(4*9-6*7)+3*(4*8-5*7)
print(detA)
print('*' * 50)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

0
**************************************************
Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


## Задание 2

Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

a) $$det(A^2)=det(A)*det(A)=16$$
б) $$det(AT)=det(A)=4$$
в) $$det(2A)=2*det(A)=8$$

## Задание 3

Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [11]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


## Задание 4

Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [13]:
# а)
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица варианта а):\n{a}')
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы варианта а): {r}')
print('*' * 50)
# б)
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица варианта б):\n{b}')
r = np.linalg.matrix_rank(b)
print(f'Ранг матрицы варианта б): {r}')

Матрица варианта а):
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы варианта а): 2
**************************************************
Матрица варианта б):
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы варианта б): 3
