<a href="https://colab.research.google.com/github/vit050587/Linear-algebra/blob/master/LinAl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
from numpy.linalg import norm
import matplotlib.pyplot as plt

# Урок 1

## Задание 1.1

Исследовать на линейную зависимость:
$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$

$$f_{3}(x)=f_{2}(x)+ x$$
$$x=f_{3}(x)-f_{2}(x), f_{4}(x)=f_{3}(x)-f_{2}(x)-f_{1}(x)$$
Вывод: один из векторов - линейная комибнация остальных, значит они линейно зависимы.

## Задание 2.1

Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}.$$

$$f_{4}(x)=f_{3}(x)+2f_{2}(x)+0.5f_{1}(x)$$
Вывод: они линейно зависимы.

## Задание 3.1

Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.

$$x=b_{2}+3b_{3}+0.5b_{1}$$

## Задание 4.1

Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

   а) в базисе $1$, $x$, $x^{2}$;

   б) в базисе $x^{2}$, $x-1$, $1$.

a) $$x=3b_{3}-2b_{2}+2b_{1}$$
б) $$x=3b_{1}-2b_{2}+0*b_{3}$$

## Задание 5.1

Установить, является ли линейным подпространством:

а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;

б) все векторы, являющиеся линейными комбинациями данных векторов  {u1,u2,...,un} .

а) $$(0,a,b)+(c,0,d)=(c,a,b+d)$$
Вывод: не принадлежат указанному множеству веторов.

б) Вывод: если векторы являются линейнными комбинациями, значит они линейно зависимы и значит являются линейным подпространством


## Задание 1.2

Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

In [14]:
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])
print(f'вариант a)(x, y) =\t{x.dot(y)}')
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
print(f'варианти б)(x, y) =\t{x.dot(y)}')

вариант a)(x, y) =	33
варианти б)(x, y) =	-23


## Задание 2.2

Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.

In [15]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])
print(f'l1 норма вектора a:\t{norm(a, ord=1)}')
print(f'l1 норма вектора b:\t{norm(b, ord=1)}')
print(f'l2 норма вектора a:\t{norm(a, ord=2)}')
print(f'l2 норма вектора b:\t{norm(b, ord=2)}')
cos_phi = np.dot(a, b) / norm(a) / norm(b)
print(f'Косинус угла между a и b: {cos_phi:.2f}')
print(f'Угол между a и b: {np.arccos(cos_phi):.2f}')

l1 норма вектора a:	10.0
l1 норма вектора b:	19.0
l2 норма вектора a:	6.0
l2 норма вектора b:	13.0
Косинус угла между a и b: 0.90
Угол между a и b: 0.46


## Задание 3.2

Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?

а) Да, но при условии если $x_{1} \mbox{ и } x_{2}$ будут коллинеарны. Если же они не коллинеарны, то норма от $x_{1} + x_{2}$ будет меньше, чем нормы от этих векторов по отдельности а значит не выполнится третья аксиома для Евклидова пространства: $(x_{1}+x_{2},y)=(x_{1},y)+(x_{2},y)$<br>
б) Да, так как выполнятся все аксиомы для Евклидова пространства

## Задание 4.2

Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>
б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>
в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>
г) $(1,0,0),(0,1,0),(0,0,1)?$ 

# Урок 2

## Задание 1.1

Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    

In [39]:
# A — матрица 4×2 , B — матрица 4×2
A = np.ones((4,2))
B = np.ones((4,2))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Матрица B
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


ValueError: ignored

In [40]:
# A — матрица 2×5 , B — матрица 5×3
A = np.ones((2,5))
B = np.ones((5,3))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Матрица B
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Матрица AB
[[5. 5. 5.]
 [5. 5. 5.]]


ValueError: ignored

In [ ]:
# A — матрица 8×3 , B — матрица 3×8
A = np.ones((8,3))
B = np.ones((3,8))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

In [ ]:
# A — квадратная матрица 4×4 , B — квадратная матрица 4×4
A = np.ones((4,4))
B = np.ones((4,4))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

## Задание 2.1

Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [ ]:
A = np.array([[1,-2],[3,0]])
B = np.array([[4,-1],[0,5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A+B\n{A+B}')
print(f'Матрица AxB\n{np.dot(A, B)}')

## Задание 3.1

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [ ]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C\n{B}')
print(f'Матрица 3A-2B+4C\n{3*A+(-2)*B+4*C}')

## Задание 4.1

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


In [ ]:
A = np.array([[4,1],[5,-2],[2,3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
print(f'матрица A*AT:\n{np.dot(A,A.T)}')
print(f'матрица AT*A:\n{np.dot(A.T,A)}')

## Задание 5.1*

Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def matrix_multiplication(m1,m2):
    s=0     # сумма
    t=[]    # временная матрица
    m3=[]   # конечная матрица
    if len(m2)!=len(m1[0]):
        print("Матрицы не соответствуют друг другу и не могут быть перемножены")        
    else:
        r1=len(m1)      # количество строк в первой матрице
        c1=len(m1[0])   # количество столбцов в первой матрице  
        r2=c1           # количество строк во второй матрице
        c2=len(m2[0])   # количество столбцов во второй матрице
        for z in range(0,r1):
            for j in range(0,c2):
                for i in range(0,c1):
                   s=s+m1[z][i]*m2[i][j]
                t.append(s)
                s=0
            m3.append(t)
            t=[]           
    return m3

## Задание 1.2

Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a) $$detA=sin^2(x)-(-cos^2(x))=1$$


In [ ]:
# б)
detA=4*(5*9-0*1)-2*(0*9-0*1)+3*(0*0-0*5)
print(detA)
print('*' * 50)
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

In [ ]:
# в)
detA=1*(5*9-8*6)-2*(4*9-6*7)+3*(4*8-5*7)
print(detA)
print('*' * 50)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

## Задание 2.2

Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

a) $$det(A^2)=det(A)*det(A)=16$$
б) $$det(AT)=det(A)=4$$
в) $$det(2A)=2*det(A)=8$$

## Задание 3.2

Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [ ]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

## Задание 4.2

Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [ ]:
# а)
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица варианта а):\n{a}')
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы варианта а): {r}')
print('*' * 50)
# б)
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица варианта б):\n{b}')
r = np.linalg.matrix_rank(b)
print(f'Ранг матрицы варианта б): {r}')

# Урок 3

## Задание 1

Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [30]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(f'Собственные числа: {w}')
print(f'Собственные вектора: \n{v}')

Собственные числа: [2. 3.]
Собственные вектора: 
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


## Задание 2

Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$$Ae_{1}=-1\\cdot e_{1}+0\\cdot e_{2}=-e_{1},$$
    
$$Ae_{2}=0\\cdot e_{1}-1\\cdot e_{2}=-e_{2}$$
  
Теперь найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}\\
-1-λ & 0\\ 0 & -1-λ
\end{vmatrix} = 0$$
    
$$(-1-λ)(-1-λ)-0*0=0,$$

$$(1+λ)^2=0$$
    
$$λ=-1.$$

Теперь найдем собственные векторы вида 
$\begin{pmatrix}x_{1}\\ x_{2}
\end{pmatrix}$
    
, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$

$$\begin{pmatrix}-1 & 0\\ 0 & -1\end{pmatrix}\begin{pmatrix}x_{1}\\ x_{2}\end{pmatrix}=\lambda\begin{pmatrix}x_{1}\\ x_{2}
\end{pmatrix}$$
  
Получим
\begin{cases}
-x_{1}+0\cdot x_{2}= -x_{1}, \\
0\cdot x_{1}-x_{2}= -x_{2}.
\end{cases}
Перенеся все в левую часть, получим
\begin{cases}
0 = 0, \\
0 = 0;
\end{cases}
    
следовательно любое $$x_{1}$$ $$x_{2}$$ удовлетворяют условиям системы уравнений


## Задание 3

Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.


In [31]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
print(f'Собственные числа: {w}')

Собственные числа: [2.00000002 1.99999998]


Получим
    
$$\begin{cases}x_{1}+x_{2}= 2x_{1}, \\-x_{1}+3x_{2}= 2x_{2}.\end{cases}$$ 
    
$$\begin{cases}x_{1} = x_{2}, \\x_{1} = x_{2};\end{cases}$$
следовательно любое $$x_{1}=x_{2}$$ удовлетворяют условиям системы уравнений и значит вектор (1,1) является собственным"

## Задание 4

Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

"Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором
$$\begin{pmatrix}0 & 3 & 0\\3 & 0 & 0\\0 & 0 & 3\end{pmatrix}\begin{pmatrix}3\\ -3\\-4\end{pmatrix}=\lambda\begin{pmatrix}\\ -3\\-4\end{pmatrix}$$,
    
Из этого будет следовать, что,
    
$$\begin{cases}-9=3\cdot\lambda \\ 9 = -3\cdot \lambda \\-12 = -4\cdot \lambda \\\end{cases}$$
система решения не имеет значит вектор не является собственным

# Урок 4

## Задание 1.1

Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Путем элементарных преобразований постараемся привести матрицу к ступенчатому виду.

Вычтем из второй строки первую, умноженную на 2:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & -3\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем из  3-ей 1-ую:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & -3\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Значит $$-2x3+3x4=4$$, система имеет множество решений. $$x_{4}=c$$ $$x_{3}=-(4-3c)/2$$ $$x_{2}=2-(4-3c)/2-3c$$ $$x_{1}=-(2-(4-3c)/2-3c)-(4-3c)/2+2c$$

## Задание 2.1

Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [32]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
a1 = np.array([[4, -1, 1], [-17, -5, -3], [0, 1, -1]])
a2 = np.array([[3, 4, 1], [2, -17, -3], [1, 0, -1]])
a3 = np.array([[3, -1, 4], [2, -5, -17], [1, 1, 0]])
det_a=np.linalg.det(a)
det_a1=np.linalg.det(a1)
det_a2=np.linalg.det(a2)
det_a3=np.linalg.det(a3)
print('определители',det_a,det_a1,det_a2,det_a3)
x1=det_a1/det_a
x2=det_a2/det_a
x3=det_a3/det_a
print('решение',x1,x2,x3)

определители 32.0 32.000000000000014 64.00000000000003 95.99999999999999
решение 1.0000000000000004 2.000000000000001 2.9999999999999996


a) значит система совместна и имеет одно решение. вектор (1,2,3)

б) методом Гаусса видно, что если из 1 уравнения вычесть 2 уравнение умноженное на 2, то получим 0=1 , а значит система решений не имеет и не совместна

в) методом гаусса обнулить 1 или 2 строку не получится, т.к. коэффициенты непропорциональны, также очевидно что уравнений меньше чем переменных, а занчит система имеет множество решений и совместна

## Задание 3.1

Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$


коэффициенты непропорциональны, количество уравнений и переменных равно. система совместна и имеет одно решение $$x_{4}=1/2$$ $$x_{3}=4/3$$ $$x_{2}=(2-1/2)/5$$ $$x_{1}=3-(2-1/2)/5+4/3-1/2$$

In [33]:
x4=1/2
x3=4/3, 
x2=(2-1/2)/5 
x1=3-(2-1/2)/5+4/3-1/2
print(x1,x2,x3,x4)

3.533333333333333 0.3 (1.3333333333333333,) 0.5


## Задание 4.1

Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a-2c
\end{matrix}
\end{pmatrix}.$$

если $$c-3a-2x$$ не равняется 0 то система является несовместной

## Задание 1.2

Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [34]:
a = np.array([[1, -2], [3, -4]])
a1 = np.array([[1, -2], [7, -4]])
a2 = np.array([[1, 1], [3, 7]])
det_a=np.linalg.det(a)
det_a1=np.linalg.det(a1)
det_a2=np.linalg.det(a2)
print('определители',det_a,det_a1,det_a2)
x1=det_a1/det_a
x2=det_a2/det_a
print('решение',x1,x2)

определители 2.0000000000000004 9.999999999999998 3.999999999999999
решение 4.999999999999998 1.9999999999999991


a) Ответ: $x_{1}=5, x_{2}=2$

In [35]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
a1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
a2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
a3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
det_a=np.linalg.det(a)
det_a1=np.linalg.det(a1)
det_a2=np.linalg.det(a2)
det_a3=np.linalg.det(a3)
print('определители',det_a,det_a1,det_a2,det_a3)
x1=det_a1/det_a
x2=det_a2/det_a
x3=det_a3/det_a
print('решение',x1,x2,x3)

определители 42.99999999999998 86.00000000000004 -43.000000000000014 42.99999999999998
решение 2.0000000000000018 -1.0000000000000009 1.0


б) Ответ $x_{1}=2, x_{2}=-1, x_{3}=1$ $$(2,-1,1)$$

## Задание 2.2

Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

## Задание 3.2

Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

## Задание 4.2

Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

## Задание 5.2*

Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.